# Generated by Django 5.2.8 on 2025-12-02 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_station_code_alter_station_geofence_radius_m_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SGL_TRANSPORT_VENDOR', 'SGL Transport Vendor'), ('FDODO_CUSTOMER', 'FDODO Customer'), ('SGL_CUSTOMER', 'SGL Customer')], max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'partners',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('license_no', models.CharField(max_length=50)),
                ('license_expiry', models.DateField()),
                ('phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20)),
                ('trained', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='logistics.partner')),
            ],
            options={
                'db_table': 'drivers',
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('priority', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=20)),
                ('requested_qty_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proposed_qty_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('dbs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals_dbs', to='core.station')),
                ('ms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals_ms', to='core.station')),
            ],
            options={
                'db_table': 'proposals',
            },
        ),
        migrations.CreateModel(
            name='StockRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('DBS_OPERATOR', 'DBS Operator'), ('FDODO_CUSTOMER', 'FDODO Customer'), ('AI', 'AI Engine')], max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('QUEUED', 'Queued'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('APPROVED', 'Approved')], default='PENDING', max_length=20)),
                ('requested_qty_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_stock_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rate_of_sale_kg_per_min', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('priority_preview', models.CharField(choices=[('H', 'High'), ('C', 'Critical'), ('N', 'Normal'), ('FDODO', 'FDODO')], default='N', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dbs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_requests', to='core.station')),
                ('requested_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.partner')),
            ],
            options={
                'db_table': 'stock_requests',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_no', models.IntegerField()),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('ms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.station')),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.proposal')),
            ],
            options={
                'db_table': 'tokens',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('AT_MS', 'At MS'), ('IN_TRANSIT', 'In Transit'), ('AT_DBS', 'At DBS'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('origin_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('dbs_arrival_at', models.DateTimeField(blank=True, null=True)),
                ('dbs_departure_at', models.DateTimeField(blank=True, null=True)),
                ('ms_return_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('rtkm_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dbs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips_destination', to='core.station')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.driver')),
                ('ms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips_origin', to='core.station')),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.proposal')),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.token')),
            ],
            options={
                'db_table': 'trips',
            },
        ),
        migrations.CreateModel(
            name='Reconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ms_filled_qty_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dbs_delivered_qty_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('diff_qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('variance_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(max_length=20)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='logistics.trip')),
            ],
            options={
                'db_table': 'reconciliation',
            },
        ),
        migrations.CreateModel(
            name='MSFilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('prefill_pressure_bar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('postfill_pressure_bar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('filled_qty_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('confirmed_by_ms_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_fillings', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ms_fillings', to='logistics.trip')),
            ],
            options={
                'db_table': 'ms_filling',
            },
        ),
        migrations.CreateModel(
            name='DBSDecanting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('pre_dec_reading', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('post_dec_reading', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('delivered_qty_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('confirmed_by_dbs_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_decantings', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dbs_decantings', to='logistics.trip')),
            ],
            options={
                'db_table': 'dbs_decanting',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('severity', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.station')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.trip')),
            ],
            options={
                'db_table': 'alerts',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_no', models.CharField(max_length=50, unique=True)),
                ('hcv_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('capacity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rfid_tag_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ms_home', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_vehicles', to='core.station')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='logistics.partner')),
            ],
            options={
                'db_table': 'vehicles',
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.vehicle'),
        ),
        migrations.AddField(
            model_name='token',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.vehicle'),
        ),
    ]
