# Generated by Django 5.2.8 on 2025-12-02 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_driver_assigned_vehicle_shift'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='stockrequest',
            name='source_partner',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='dbs',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='ms',
        ),
        migrations.RemoveField(
            model_name='token',
            name='proposal',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='proposal',
        ),
        migrations.AddField(
            model_name='driver',
            name='vendor',
            field=models.ForeignKey(default=1, limit_choices_to={'user_roles__role__code': 'SGL_TRANSPORT_VENDOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockrequest',
            name='source_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_requests_as_vendor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vendor',
            field=models.ForeignKey(default=1, limit_choices_to={'user_roles__role__code': 'SGL_TRANSPORT_VENDOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stockrequest',
            name='requested_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_requests_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Partner',
        ),
        migrations.DeleteModel(
            name='Proposal',
        ),
    ]
