# Generated by Django 5.2.8 on 2025-12-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_stockrequest_rejected_at_stockrequest_rejected_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrequest',
            name='requested_by_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockrequest',
            name='requested_by_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
