# Generated by Django 5.2.8 on 2025-12-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_stockrequest_requested_by_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrequest',
            name='approval_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
