# Generated by Django 5.2.8 on 2025-12-03 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_stockrequest_approval_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrequest',
            name='assignment_mode',
            field=models.CharField(blank=True, choices=[('AUTO', 'Auto-Push'), ('MANUAL', 'Manual Assignment')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='stockrequest',
            name='assignment_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockrequest',
            name='target_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offered_requests', to='logistics.driver'),
        ),
        migrations.AddField(
            model_name='trip',
            name='stock_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip', to='logistics.stockrequest'),
        ),
        migrations.AlterField(
            model_name='stockrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('QUEUED', 'Queued'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('APPROVED', 'Approved'), ('ASSIGNING', 'Assigning Driver'), ('ASSIGNED', 'Driver Assigned')], default='PENDING', max_length=20),
        ),
    ]
