# Generated by Django 5.2.8 on 2025-12-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0008_stockrequest_assignment_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='ms_departure_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='sto_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
