# Generated by Django 5.2.8 on 2025-12-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0009_trip_ms_departure_at_trip_sto_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbsdecanting',
            name='post_dec_pressure_bar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dbsdecanting',
            name='pre_dec_pressure_bar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='msfilling',
            name='postfill_mfm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='msfilling',
            name='prefill_mfm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='msfilling',
            name='topup_pressure_bar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
