# Generated by Django 5.2.8 on 2025-12-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0010_dbsdecanting_post_dec_pressure_bar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('QUEUED', 'Queued'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('APPROVED', 'Approved'), ('ASSIGNING', 'Assigning Driver'), ('ASSIGNED', 'Driver Assigned'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
    ]
