# Generated by Django 5.2.8 on 2025-12-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0011_alter_stockrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='unique_code',
            field=models.CharField(editable=False, max_length=16, null=True, unique=True),
        ),
    ]
