# Generated by Django 5.2.8 on 2025-12-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0012_token_unique_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='sequence_no',
        ),
        migrations.RemoveField(
            model_name='token',
            name='unique_code',
        ),
        migrations.AddField(
            model_name='token',
            name='token_no',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
