# Generated by Django 5.2.8 on 2025-12-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0013_remove_token_sequence_no_remove_token_unique_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('AT_MS', 'At MS'), ('IN_TRANSIT', 'In Transit'), ('AT_DBS', 'At DBS'), ('DECANTING_CONFIRMED', 'Decanting Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=50),
        ),
    ]
