# Generated by Django 5.2.8 on 2025-12-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0015_trip_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shift',
            name='recurrence_pattern',
            field=models.CharField(default='NONE', max_length=20),
        ),
    ]
