# Generated by Django 5.2.8 on 2025-12-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0016_shift_is_recurring_shift_recurrence_pattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
