# Generated by Django 5.2.8 on 2025-12-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0017_shift_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='license_verified',
            field=models.BooleanField(default=False),
        ),
    ]
