# Generated by Django 5.2.8 on 2025-12-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0018_driver_license_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbsdecanting',
            name='post_decant_photo',
            field=models.ImageField(blank=True, null=True, upload_to='dbs_decantings/post/'),
        ),
        migrations.AddField(
            model_name='dbsdecanting',
            name='pre_decant_photo',
            field=models.ImageField(blank=True, null=True, upload_to='dbs_decantings/pre/'),
        ),
        migrations.AddField(
            model_name='msfilling',
            name='postfill_photo',
            field=models.ImageField(blank=True, null=True, upload_to='ms_fillings/post/'),
        ),
        migrations.AddField(
            model_name='msfilling',
            name='prefill_photo',
            field=models.ImageField(blank=True, null=True, upload_to='ms_fillings/pre/'),
        ),
    ]
