# Generated by Django 5.2.8 on 2025-12-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0020_trip_step_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrequest',
            name='requested_qty_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
