# Generated by Django 5.2.8 on 2025-12-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0021_alter_stockrequest_requested_qty_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbsdecanting',
            name='post_decant_photo_operator',
            field=models.ImageField(blank=True, null=True, upload_to='dbs_decantings/post/operator/'),
        ),
        migrations.AddField(
            model_name='dbsdecanting',
            name='pre_decant_photo_operator',
            field=models.ImageField(blank=True, null=True, upload_to='dbs_decantings/pre/operator/'),
        ),
        migrations.AddField(
            model_name='msfilling',
            name='postfill_photo_operator',
            field=models.ImageField(blank=True, null=True, upload_to='ms_fillings/post/operator/'),
        ),
        migrations.AddField(
            model_name='msfilling',
            name='prefill_photo_operator',
            field=models.ImageField(blank=True, null=True, upload_to='ms_fillings/pre/operator/'),
        ),
        migrations.AlterField(
            model_name='dbsdecanting',
            name='post_decant_photo',
            field=models.ImageField(blank=True, null=True, upload_to='dbs_decantings/post/driver/'),
        ),
        migrations.AlterField(
            model_name='dbsdecanting',
            name='pre_decant_photo',
            field=models.ImageField(blank=True, null=True, upload_to='dbs_decantings/pre/driver/'),
        ),
        migrations.AlterField(
            model_name='msfilling',
            name='postfill_photo',
            field=models.ImageField(blank=True, null=True, upload_to='ms_fillings/post/driver/'),
        ),
        migrations.AlterField(
            model_name='msfilling',
            name='prefill_photo',
            field=models.ImageField(blank=True, null=True, upload_to='ms_fillings/pre/driver/'),
        ),
    ]
