# Generated by Django 5.2.8 on 2025-12-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0022_dbsdecanting_post_decant_photo_operator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='ms_arrival_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='ms_arrival_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('AT_MS', 'At MS'), ('IN_TRANSIT', 'In Transit'), ('AT_DBS', 'At DBS'), ('DECANTING_CONFIRMED', 'Decanting Confirmed'), ('RETURNED_TO_MS', 'Returned to MS'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=50),
        ),
    ]
