# Generated by Django 5.2.8 on 2025-12-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0023_trip_ms_arrival_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='dbs_arrival_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='dbs_arrival_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
