# Generated by Django 5.2.8 on 2026-01-06 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0025_shift_notes_shifttemplate_shift_shift_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='capacity_kg',
        ),
    ]
