# Generated by Django 5.2.8 on 2026-01-06 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0026_remove_vehicle_capacity_kg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shifttemplate',
            name='updated_at',
        ),
    ]
