# Generated by Django 5.2.8 on 2026-01-06 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0027_remove_shifttemplate_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shifttemplate',
            name='created_by',
        ),
    ]
