# Generated by Django 5.2.8 on 2026-01-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0028_remove_shifttemplate_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='license_document',
            field=models.FileField(blank=True, help_text='Driver license document (PDF, PNG, JPG). Max 5MB.', null=True, upload_to='drivers/licenses/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='registration_document',
            field=models.FileField(blank=True, help_text='Vehicle registration document (PDF, PNG, JPG). Max 5MB.', null=True, upload_to='vehicles/documents/'),
        ),
    ]
