# Generated by Django 5.2.8 on 2026-01-06 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_token_queue_system'),
        ('logistics', '0029_driver_license_document_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When EIC approved this request', null=True),
        ),
        migrations.AddField(
            model_name='stockrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_stock_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockrequest',
            name='queue_position',
            field=models.PositiveIntegerField(blank=True, help_text='Position in approval queue for FCFS ordering', null=True),
        ),
        migrations.CreateModel(
            name='VehicleToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_no', models.CharField(help_text='Format: MS{ms_id}-{date}-{seq}', max_length=30, unique=True)),
                ('sequence_number', models.PositiveIntegerField(help_text='Daily sequence per MS, resets at midnight')),
                ('token_date', models.DateField(help_text='Date for sequence reset tracking')),
                ('status', models.CharField(choices=[('WAITING', 'Waiting in Queue'), ('ALLOCATED', 'Allocated to Trip'), ('EXPIRED', 'Expired/Cancelled')], default='WAITING', max_length=20)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('allocated_at', models.DateTimeField(blank=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('expiry_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_tokens', to='logistics.driver')),
                ('ms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_tokens', to='core.station')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tokens', to='logistics.shift')),
                ('trip', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_token', to='logistics.trip')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_tokens', to='logistics.vehicle')),
            ],
            options={
                'db_table': 'vehicle_tokens',
                'ordering': ['token_date', 'sequence_number'],
            },
        ),
        migrations.AddField(
            model_name='stockrequest',
            name='allocated_vehicle_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_requests', to='logistics.vehicletoken'),
        ),
        migrations.AddIndex(
            model_name='stockrequest',
            index=models.Index(fields=['status', 'approved_at'], name='stock_reque_status_82fc3f_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicletoken',
            index=models.Index(fields=['ms', 'status', 'token_date'], name='vehicle_tok_ms_id_8819e7_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicletoken',
            index=models.Index(fields=['driver', 'status'], name='vehicle_tok_driver__f51901_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicletoken',
            index=models.Index(fields=['token_date', 'sequence_number'], name='vehicle_tok_token_d_66ed44_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vehicletoken',
            unique_together={('ms', 'token_date', 'sequence_number')},
        ),
    ]
