# Generated by Django 5.2.8 on 2025-12-01 06:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique role code identifier (e.g., SUPER_ADMIN, MS_OPERATOR)', max_length=100, unique=True, verbose_name='Role Code')),
                ('name', models.CharField(help_text='Human-readable role name', max_length=100, verbose_name='Role Name')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the role', null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the station', max_length=255, verbose_name='Station Name')),
            ],
            options={
                'verbose_name': 'Station',
                'verbose_name_plural': 'Stations',
                'db_table': 'stations',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(help_text='User email address (used for login)', max_length=254, unique=True, verbose_name='Email Address')),
                ('full_name', models.CharField(help_text="User's full name", max_length=255, verbose_name='Full Name')),
                ('phone', models.CharField(help_text='Contact phone number', max_length=20, verbose_name='Phone Number')),
                ('role_in', models.DateTimeField(blank=True, help_text="User's role in date-time", null=True, verbose_name='Role In Date')),
                ('role_out', models.DateTimeField(blank=True, help_text="User's role out date-time", null=True, verbose_name='Role Out Date')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user account is active', verbose_name='Active Status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into the admin site', verbose_name='Staff Status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, help_text='Whether this role assignment is currently active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('role', models.ForeignKey(help_text='Role assigned to the user', on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='core.role', verbose_name='Role')),
                ('station', models.ForeignKey(blank=True, help_text='Station where this role is assigned (optional for Super Admins)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_roles', to='core.station', verbose_name='Station')),
                ('user', models.ForeignKey(help_text='User assigned to this role', on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Role',
                'verbose_name_plural': 'User Roles',
                'db_table': 'user_roles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'active'], name='user_roles_user_id_3ea90d_idx'), models.Index(fields=['role', 'active'], name='user_roles_role_id_5fa180_idx'), models.Index(fields=['station', 'active'], name='user_roles_station_e2a34b_idx')],
                'unique_together': {('user', 'role', 'station')},
            },
        ),
    ]
