# Generated by Django 5.2.8 on 2025-12-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='station',
            options={'ordering': ['name'], 'verbose_name': 'Station', 'verbose_name_plural': 'Stations'},
        ),
        migrations.AddField(
            model_name='station',
            name='address',
            field=models.CharField(blank=True, help_text='Station street address or site description.', max_length=500, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='station',
            name='city',
            field=models.CharField(blank=True, help_text='City where the station is located.', max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='station',
            name='code',
            field=models.CharField(blank=True, help_text='Unique identifier for the station (e.g., MS001).', max_length=50, null=True, unique=True, verbose_name='Station Code'),
        ),
        migrations.AddField(
            model_name='station',
            name='geofence_radius_m',
            field=models.PositiveIntegerField(blank=True, help_text='Geofence radius in meters (default 200).', null=True, verbose_name='Geofence Radius (m)'),
        ),
        migrations.AddField(
            model_name='station',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS latitude (decimal degrees).', max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='station',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS longitude (decimal degrees).', max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='station',
            name='type',
            field=models.CharField(blank=True, choices=[('MS', 'Mother Station'), ('DBS', 'Daughter Booster Station')], help_text='Station category: Mother Station (MS) or Daughter Booster Station (DBS). Optional.', max_length=3, null=True, verbose_name='Station Type'),
        ),
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(blank=True, help_text='Human-friendly station name.', max_length=255, null=True, verbose_name='Station Name'),
        ),
    ]
