# Generated by Django 5.2.8 on 2025-12-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_station_options_station_address_station_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='code',
            field=models.CharField(default='TEMP', help_text='Unique identifier for the station (e.g., MS001).', max_length=50, unique=True, verbose_name='Station Code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='station',
            name='geofence_radius_m',
            field=models.PositiveIntegerField(default=200, help_text='Geofence radius in meters (default 200).', verbose_name='Geofence Radius (m)'),
        ),
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(default='Station', help_text='Human-friendly station name.', max_length=255, verbose_name='Station Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='station',
            name='type',
            field=models.CharField(choices=[('MS', 'Mother Station'), ('DBS', 'Daughter Booster Station')], default='MS', help_text='Station category: Mother Station (MS) or Daughter Booster Station (DBS).', max_length=3, verbose_name='Station Type'),
            preserve_default=False,
        ),
    ]
