# Generated by Django 5.2.8 on 2025-12-02 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_station_code_alter_station_geofence_radius_m_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='parent_station',
            field=models.ForeignKey(blank=True, help_text='Parent Mother Station (for DBS only).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daughter_stations', to='core.station', verbose_name='Parent Station'),
        ),
    ]
