# Generated by Django 5.2.8 on 2025-12-02 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_station_parent_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('planned_rtkm_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('dbs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_to', to='core.station')),
                ('ms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_from', to='core.station')),
            ],
            options={
                'db_table': 'routes',
            },
        ),
        migrations.CreateModel(
            name='MSDBSMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('dbs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ms_mappings', to='core.station')),
                ('ms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dbs_mappings', to='core.station')),
            ],
            options={
                'db_table': 'ms_dbs_map',
                'unique_together': {('ms', 'dbs')},
            },
        ),
    ]
