# Generated by Django 5.2.8 on 2025-12-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_fcm_token_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='capacity_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total storage capacity for the station in kilograms.', max_digits=12, null=True, verbose_name='Capacity (kg)'),
        ),
        migrations.AddField(
            model_name='station',
            name='current_stock_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Latest recorded stock for the station in kilograms.', max_digits=12, null=True, verbose_name='Current Stock (kg)'),
        ),
        migrations.AddField(
            model_name='station',
            name='stock_updated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the latest stock update.', null=True, verbose_name='Stock Updated At'),
        ),
    ]
