# Generated by Django 5.2.8 on 2025-12-09 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_station_capacity_kg_station_current_stock_kg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique permission identifier (e.g., can_raise_manual_request)', max_length=100, unique=True, verbose_name='Permission Code')),
                ('name', models.CharField(help_text='Human-readable permission name', max_length=100, verbose_name='Permission Name')),
                ('description', models.TextField(blank=True, help_text='Detailed description of what this permission allows', null=True, verbose_name='Description')),
                ('category', models.CharField(choices=[('requests', 'Stock Requests'), ('trips', 'Trips'), ('drivers', 'Drivers'), ('stations', 'Stations'), ('tokens', 'Tokens'), ('system', 'System')], default='system', help_text='Permission category for grouping in UI', max_length=50, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'db_table': 'permissions',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted', models.BooleanField(default=True, help_text='Whether this permission is granted (True) or denied (False)', verbose_name='Granted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permission', models.ForeignKey(help_text='Permission granted to this role', on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='core.permission', verbose_name='Permission')),
                ('role', models.ForeignKey(help_text='Role this permission is assigned to', on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='core.role', verbose_name='Role')),
            ],
            options={
                'verbose_name': 'Role Permission',
                'verbose_name_plural': 'Role Permissions',
                'db_table': 'role_permissions',
                'ordering': ['role__name', 'permission__category', 'permission__name'],
                'unique_together': {('role', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted', models.BooleanField(default=True, help_text='Whether this permission is granted (True) or revoked (False)', verbose_name='Granted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin who created this override', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_user_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('permission', models.ForeignKey(help_text='Permission being overridden', on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='core.permission', verbose_name='Permission')),
                ('user', models.ForeignKey(help_text='User this permission override applies to', on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions_custom', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Permission',
                'verbose_name_plural': 'User Permissions',
                'db_table': 'user_permissions',
                'ordering': ['user__full_name', 'permission__category', 'permission__name'],
                'unique_together': {('user', 'permission')},
            },
        ),
    ]
