# Generated by Django 5.2.8 on 2025-12-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_permission_rolepermission_userpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone number for the station.', max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='station',
            name='sap_last_synced_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last successful sync with SAP.', null=True, verbose_name='Last SAP Sync'),
        ),
        migrations.AddField(
            model_name='station',
            name='sap_station_id',
            field=models.CharField(blank=True, help_text='Station ID from SAP system (INPUT1). Used for synchronization.', max_length=50, null=True, unique=True, verbose_name='SAP Station ID'),
        ),
    ]
