# Generated by Django 5.2.8 on 2025-12-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_station_phone_station_sap_last_synced_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sap_last_synced_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last successful sync with SAP.', null=True, verbose_name='Last SAP Sync'),
        ),
    ]
