# Generated by Django 5.2.8 on 2025-12-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_user_sap_last_synced_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_password_reset_required',
            field=models.BooleanField(default=False, help_text='Designates whether the user must reset their password on next login', verbose_name='Password Reset Required'),
        ),
        migrations.AddField(
            model_name='user',
            name='mpin',
            field=models.CharField(blank=True, help_text='4-digit MPIN for quick login (hashed)', max_length=128, null=True, verbose_name='MPIN'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(help_text='Contact phone number', max_length=20, unique=True, verbose_name='Phone Number'),
        ),
    ]
