# Generated by Django 5.2.8 on 2025-12-12 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_user_is_password_reset_required_user_mpin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=6, verbose_name='OTP Code')),
                ('reset_token', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Secure Reset Token')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'password_reset_sessions',
            },
        ),
    ]
