# Generated by Django 5.2.8 on 2026-01-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_passwordresetsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, help_text='User email address (used for login)', max_length=254, null=True, unique=True, verbose_name='Email Address'),
        ),
    ]
