# Generated by Django 5.2.8 on 2026-01-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='platform',
            field=models.CharField(choices=[('all', 'All Platforms'), ('mobile', 'Mobile App Only'), ('dashboard', 'Web Dashboard Only')], default='all', help_text='Which platform this permission applies to (mobile, dashboard, or all)', max_length=20, verbose_name='Platform'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='category',
            field=models.CharField(choices=[('requests', 'Stock Requests'), ('trips', 'Trips'), ('drivers', 'Drivers'), ('stations', 'Stations'), ('tokens', 'Tokens'), ('screens', 'Screen Access'), ('system', 'System')], default='system', help_text='Permission category for grouping in UI', max_length=50, verbose_name='Category'),
        ),
    ]
