# Generated by Django 5.2.8 on 2026-01-07 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_token_queue_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted', models.BooleanField(default=True, help_text='Whether this permission is granted', verbose_name='Granted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permission', models.ForeignKey(help_text='Permission granted/revoked', on_delete=django.db.models.deletion.CASCADE, related_name='station_permissions', to='core.permission', verbose_name='Permission')),
                ('station', models.ForeignKey(help_text='Station this permission applies to', on_delete=django.db.models.deletion.CASCADE, related_name='station_permissions', to='core.station', verbose_name='Station')),
            ],
            options={
                'verbose_name': 'Station Permission',
                'verbose_name_plural': 'Station Permissions',
                'db_table': 'station_permissions',
                'ordering': ['station__name', 'permission__category', 'permission__name'],
                'unique_together': {('station', 'permission')},
            },
        ),
    ]
