# Generated by Django 5.2.8 on 2026-01-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_stationpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='no_of_bays',
            field=models.PositiveIntegerField(default=2, help_text='Number of filling bays available at this station (MS only).', verbose_name='Number of Bays'),
        ),
    ]
